### ISSUE TITLE
VisualStudio 2017 errors

### ISSUE THREAD

**Issue by Harkanork** [versatica/libmediasoupclient#103]
When compiling the LibMediaSoupClient with VisualStudio 2017 x64, i have the following errors

3>Consumer.cpp
3>webrtc-84\src\rtc_base/string_to_number.h(63): error C2220: avertissement considéré comme une erreur - aucun fichier 'object' généré
3>webrtc-84\src\rtc_base/string_to_number.h(63): warning C4003: pas assez d'arguments pour l'appel de macro de type fonction 'max'
...
Sorry for the french error messages, but it says that there is a conflict with the max macro
To avoid this I had to apply the following patch
[libmediasoupclient_VisualStudio2017.zip](https://github.com/versatica/libmediasoupclient/files/5407509/libmediasoupclient_VisualStudio2017.zip)

**Comment by ibc** [comment]
Please don't send zip files. Make a PR instead. Thanks

**Comment by Harkanork** [comment]
Hi,

Nice idea, but I can't:
remote: Permission to versatica/libmediasoupclient.git denied to Harkanork.
fatal: unable to access '
https://github.com/versatica/libmediasoupclient.git/': The requested URL
returned error: 403
Pushing to https://github.com/versatica/libmediasoupclient.git

**Comment by ibc** [comment]
You don't have permission to push to the libmediasoupclient project. Nobody has but just authors. Fork the project and create a Pull Request.
