### ISSUE TITLE
Not propagating maxaveragebitrate in Mediaselection

### ISSUE THREAD

**Issue by GEverding** [versatica/libmediasoupclient#130]
it appears that `maxaveragebitrate` isn't propaged to the sdp codec options. The js code does set it [here](https://github.com/versatica/mediasoup-client/blob/4aa873afa6be1469d11d34f1489a699c838ae081/lib/handlers/sdp/MediaSection.js#L148). 

Would this prevent me from setting bitrate for opus?

**Comment by ibc** [comment]
Please, use the forum for questions.
