### ISSUE TITLE
Unlimited increase of sdp information

### ISSUE THREAD

**Issue by Ripple-qin** [versatica/libmediasoupclient#137]
If the caller repeatedly switches the camera on and off 100 times, the sdp information of the callee will generate 100 m lines, 99 of which are inactive. Why not delete the inactive m lines to avoid unlimited increase of sdp information? it will slow down the parsing speed of sdp json.

_**why not remove close mediaSection from this->sdpObject?**_
```
void Sdp::RemoteSdp::CloseMediaSection(const std::string& mid) 
	{
		MSC_TRACE();

		const auto idx     = this->midToIndex[mid];
		auto* mediaSection = this->mediaSections[idx];
      
		// NOTE: Closing the first m section is a pain since it invalidates the
		// bundled transport, so let's avoid it.
                 if (mid == this->firstMid) {
                     mediaSection->Disable();
                 } else {
                     mediaSection->Close();
                 }
		// Update SDP media section.
		this->sdpObject["media"][idx] = mediaSection->GetObject();
		// Regenerate BUNDLE mids.
		this->RegenerateBundleMids();
	}
```

should be change to ?

```
        auto result = find_if(this->mediaSections.begin(),this->mediaSections.end(),[](MediaSection* content) {
            return content->IsClosed();
        });
        
        if (result != this->mediaSections.end())
        {
            this->ReplaceMediaSection(mediaSection,(*result)->GetMid());
        }
        else
        {
            this->AddMediaSection(mediaSection);
        }
```

**Comment by ibc** [comment]
Closed or inactive m= sections cannot me removed from a SDP. Please read the RFC that defines SDP.

**Comment by Ripple-qin** [comment]
> Closed or inactive m= sections cannot me removed from a SDP. Please read the RFC that defines SDP.

sorry to disturb you again. Why has this link changed? Isn't reuse similar to delete? @ibc 
Same as this: versatica/mediasoup-client@c0da308
