### ISSUE TITLE
Support webrtc M98

### ISSUE THREAD

**Issue by Ripple-qin** [versatica/libmediasoupclient#141]
Hello, author, sorry to disturb you.
We want to upgrade the webrtc native library to M98. Does the corresponding libmediasoupclient already support it? If we upgrade libmediasoupclient to the latest release 3.3.0, Does the corresponding server mediasoup need to be upgraded? Do they have a corresponding relationship?
Thanks in advance for your answer

**Comment by ibc** [comment]
Questions in the public forum, please.
