### ISSUE TITLE
use libmediasoup  why no callback msg？

### ISSUE THREAD

**Issue by jackwxs** [versatica/libmediasoupclient#143]
![image](https://user-images.githubusercontent.com/28855943/170830940-9bcce53e-8f66-4453-a902-5b1b773b5baf.png)
![image](https://user-images.githubusercontent.com/28855943/170830983-5095507a-7557-48b2-acff-e0a5e27cfe6e.png)

![image](https://user-images.githubusercontent.com/28855943/170830963-3b162591-5e12-4271-a498-7583188f0e53.png)

**Comment by ibc** [comment]
Use the forum for questions.
