### ISSUE TITLE
Add support for FlexFEC

### ISSUE THREAD

**Issue by orgotF** [versatica/libmediasoupclient#148]
I have added WebRTC's FlexFEC module to the Mediasoup，but I don't know how to enable the flexfec on the libmediasoupclient.
I just know it needs to add "WebRTC-FlexFEC-03/Enabled/WebRTC-FlexFEC-03-Advertised/Enabled", so what do I need to do next?

**Comment by ibc** [comment]
This is a pure libwebrtc related question. Please ask in the corresponding forum.
