### ISSUE TITLE
videoGoogleMaxBitrate 

### ISSUE THREAD

**Issue by jzdcf** [versatica/libmediasoupclient#166]
When I set the maximum bitrate, my first reaction was to use the videoGoogleMaxBitrate parameter based on the document, but it didn't work. I had no choice but to use max_bitrate_bps in webrtc:: RtpEncodingParameters has taken effect this time. Is the videoGoogleMaxBitrate of the document useless?

**Comment by ibc** [comment]
Use the mediasoup forum for questions, please.
