### ISSUE TITLE
Upgraded to WebRTC m120-6099

### ISSUE THREAD

**Issue by janreyho** [versatica/libmediasoupclient#178]
I’ve upgraded `libmediasoupclient` to WebRTC m120-6099 and also updated the corresponding test demo, `mediasoup-broadcaster-demo` to the same version.

This upgrade allows for successful room entry and video stream publishing.

Testing on a Mac with an M3 Max chip has been successful.

**Comment by ibc** [comment]
Please contribute to the m120 ongoing PR in which we have some blocker problems to complete it:

https://github.com/versatica/libmediasoupclient/pull/173
