### ISSUE TITLE
produce(): If the app gives a single encoding keep its members in the generated RtpParameters

### ISSUE THREAD

**Issue by ibc** [versatica/libmediasoupclient#29]
Related commit in mediasoup-client JS: https://github.com/versatica/mediasoup-client/commit/c63defc81e01b1fa08d5715b3f8e4650011d68bd?ts=2

This makes it possible to set `maxBitrate` or `dtx`, etc in a single encoding (for audio, for instance, or video with no simulcast).

**NOTE:** This is just for Chrome >= 75.

**Comment by jmillan** [comment]
done 6f43d86b6b94906d5a2a6a2c463351cc651888a5
