### ISSUE TITLE
Fatal error: api/media_stream_interface.h: No such file or directory

### ISSUE THREAD

**Issue by Risingmobi** [versatica/libmediasoupclient#39]
Hi. I have download and compiled webrtc sources for Android OS. But when I am trying to compile mediasoup with links to WebRTC - I am getting this error: 
/MediaSoupClient/libmediasoupclient/include/Consumer.hpp:6:69: fatal error: api/media_stream_interface.h: No such file or directory

This is my links to WebRTC sources
cmake . -Bbuild \
-DLIBWEBRTC_INCLUDE_PATH:PATH=$/media/0872773872772A183/Android_Dev/projects/WebRTCSources/WEBRTC/src/ \
-DLIBWEBRTC_BINARY_PATH:PATH=$/media/0872773872772A183/Android_Dev/projects/WebRTCSources/WEBRTC/src/build

On this screen you can see the contents of WebRTC sources
http://joxi.ru/LmGvVM6UwJE4Zr

I am using 73 branch and doble-checked that api folder contains media_stream_interface.h

Could you please help me and tell what I am doing wrong? may something wrong with the paths?

**Comment by ibc** [comment]
Remove the $ symbols.
