### ISSUE TITLE
Create react-native-mediasoupclient

### ISSUE THREAD

**Issue by ibc** [versatica/libmediasoupclient#40]
Instead of using the super outdated **react-native-webrtc** (which poorly implements a WebRTC API of 2013) we should create **react-native-mediasoupclient** (based on libmediasoupclient, of course).

Let's this issue stay here until we initiate the new project.

**Comment by Sharcoux** [comment]
Would this be just an implementation of webrtc for react-native, or an implementation of webrtc specially designed for mediasoup?

**Comment by ibc** [comment]
libmediasoupclient is not a "generic" WebRTC stack. It exposes a [C++ API](https://mediasoup.org/documentation/v3/libmediasoupclient/api/). By using libmediasoupclient plus some Java/ObjC kung-fu plus some react-native JS, we can build `react-native-mediasoupclient` which, as any other react-native library, would expose a JS API. Such a JS API should be similar to the [JS API](https://mediasoup.org/documentation/v3/mediasoup-client/api/) exposed by mediasoup-client.

**Comment by Sharcoux** [comment]
:/
Wouldn't it be much better to create a react-native project that would expose an API identical to the webrtc API we have on the web?

By the way, `react-native-webrtc` is not that far from this goal in their last version. There is just that terrible management of the tracks which sucks and needs to be fixed.

**Comment by ibc** [comment]
> Wouldn't it be much better to create a react-native project that would expose an API identical to the webrtc API we have on the web?

Definitely that's a legit approach. I'm not against that.
 
> By the way, `react-native-webrtc` is not that far from this goal in their last version. There is just that terrible management of the tracks which sucks and needs to be fixed.

And a super outdated API from 2013.

**Comment by Sharcoux** [comment]
I believe that the last versions fixed most of that. I used to have a bridge between their api and the browser api but I could remove it all when I updated last week. But I'm using only some part of the api so maybe the rest didn't evolve.

**Comment by ibc** [comment]
The exposed API still relies on streams (like the original WebRTC API in 2013). Neither track based API nor transceiver API. It has evolved nothing IMHO.

**Comment by Sharcoux** [comment]
Ok. We are not talking about the same thing. Then you are probably right.

Le mar. 7 mai 2019 à 19:23, Iñaki Baz Castillo <notifications@github.com> a
écrit :

**Comment by philjoseph** [comment]
So for now we cannot develop a react-native mobile apps to consume your JS mediasoupclient  and your mediasoup server ? Your JS lib will not work ok with the native Android and native iOS web rtc libraries https://webrtc.org/native-code/ios/ and https://webrtc.org/native-code/android

**Comment by ibc** [comment]
@saghul is working super hard in making react-native-webrtc a proper and modern WebRTC implementation for React-Native, so let's forget and close this topic :)
