### ISSUE TITLE
Is it possible to compile mediasoup v3 for usage in Android project?

### ISSUE THREAD

**Issue by Risingmobi** [versatica/libmediasoupclient#42]
Hi. I am trying to compile and use mediasoup client library and then use it im my Android project
I am wondering if it is possible at all? 
According to the documentation - to compile mediasoup - at first we need to compile webrtc and provide paths to webrtc sources and binaries to the CMake script of mediasoup
But the documentation talks us to compile webrtc as a static library (for desktop platforms) - but this static library cannot be used in android, because android is working with shared libraries and the compilation process for android is a bit different that standard webrtc compilation. I have compiled webrtc and got and webrtc.aar library as a result. Then I have provided paths to this .aar file and to webrtc sources into the mediasoup build script and have got a static mediasoup .a library. 
But when I have imported them into my android project and tried to get an access to mediasoup classes from my android C++ code - I have got lots of exceptions about missing references between mediasoup, libsdptransform and webrtc. I think this happens because of wrong compilation params or something like this. Maybe because webrtc was compiled for android like an .aar file and not .a library
Could you please tell me is it really possible to compile and use mediasoup v3 client library with webrtc in android project?
And if it is possible - could you please describe me basic steps of how they all can be compiled and placed together?

**Comment by jmillan** [comment]
Hi,

We tested libmediasoupclient in Linux, MacOS and Windows platform. We'll document how to build it in mobile platforms as soon as we test it.

**Comment by Risingmobi** [comment]
Okay. Thank you. Will be waiting for your response. I really need to implement libmediasoup client on Android OS and will be very pleased for you

**Comment by ibc** [comment]
> Okay. Thank you. Will be waiting for your response. I really need to implement libmediasoup client on Android OS and will be very pleased for you

We do not have much experience in Android/iOS development, so our "response" may take long (until for some reason we need to enter into that world). So if you could contribute by checking the required changes in the CMakeList.txt etc to use dynamic libs it would be great. Definitely we don't have time/resources to maintain everything and test it in all possible platforms and scenarios and cannot become experts in all them.

**Comment by pcgpcgpcg** [comment]
I think there are two way for Android:
(1) manual compile webrtc Android,then you get libpeerconnection_so.so and libwebrtc.jar
     manual add libmediasoup's cpp code and let it call libpeerconnection_so.so
(2) add jni wrapper for libmediasoup's cpp code ,call everything on the Java layer.
     The reason is webrtc android's hw codec and camera2 interface etc..... lauch on the java layer

**Comment by Risingmobi** [comment]
> > Okay. Thank you. Will be waiting for your response. I really need to implement libmediasoup client on Android OS and will be very pleased for you
> 
> We do not have much experience in Android/iOS development, so our "response" may take long (until for some reason we need to enter into that world). So if you could contribute by checking the required changes in the CMakeList.txt etc to use dynamic libs it would be great. Definitely we don't have time/resources to maintain everything and test it in all possible platforms and scenarios and cannot become experts in all them.

I will be very glad to make contributions and help you for crating mediasoup library for Android. But I don't know from what point to start. I have compiled the libs - but when I am starting linking them into my C++ code - to create a wrapper between C side and Kotlin side - I have lots of exceptions. So I need a little push (an advice) about how to compile them to be used in GreenRobot(

**Comment by ibc** [comment]
If we had to learn about Kotlin and GreenRobot (no idea what that is) in order to help you, then we'd not need you to contribute :)

The thing here is that we just don't know about that, so we cannot provide "a little push" like if we already knew about it.

**Comment by Risingmobi** [comment]
> I think there are two way for Android:
> (1) manual compile webrtc Android,then you get libpeerconnection_so.so and libwebrtc.jar
> manual add libmediasoup's cpp code and let it call libpeerconnection_so.so
> (2) add jni wrapper for libmediasoup's cpp code ,call everything on the Java layer.
> The reason is webrtc android's hw codec and camera2 interface etc..... lauch on the java layer

Oh!! I didn't think about this) So you are talking about - not to compile mediasoup by itself? 
So the basic idea - compile webrtc and libpeerconnection? Then link them into android's native project, copy mediasoups code directly into the project - and then starting making the wrapper? And what about libsdptransform?

**Comment by Risingmobi** [comment]
> If we had to learn how Kotlin and GreenRobot (no idea what that is) in order to help you, then we'd not need you to contribute :)
> 
> The thing here is that we just don't know about that, so we cannot provide "a little push" like if we already knew about it.


GreenRobot - Android)) I was kidding)) I have only one trouble - how to link the compiled libraries together. Android Studio - can see the dependencies between libraries. But when I am trying to compile my project - I am getting a lot of exceptions about unsatisfied dependencies. So this may be a good Idea - not to compile mediasoup client by itself, but import the code into my project, link it there to webrtc and try to do some actions. I'll try - and then write about my progress

**Comment by ibc** [comment]
Hi @Risingmobi, anything to add about this? we don't want to keep open issues that we cannot solve right now.

**Comment by caseyyee** [comment]
@Risingmobi I am wondering if you had any luck with this.  I'm wanting to use mediasoup v3 on Android as well.  Any resources, tips and links you could share would be useful!

**Comment by hhvdblom** [comment]
In day-to-day live I work as a Microsoft Software Architect/Developer.  If I use a library in my IDE I just reference libraries. In MediaSoup you have to load lots of files, compile those etc. I was wondering whats the Idea behind that?

**Comment by ibc** [comment]
@hhvdblom: feel free to contribute to the project with a better build system. We don't use Windows and are fine with the CMake based system exposed by libmediasoupclient. You have paid nothing for this project so, instead of complaining, contribute to it if you need changes.
