### ISSUE TITLE
How to build libmediasoupclient for Windows?

### ISSUE THREAD

**Issue by Eldorado3** [versatica/libmediasoupclient#43]
Hi, 

I am trying to build libmediasoupclient for Windows on a Windows 10 machine. I have successfully built webrtc.lib in the m73 branch, but when I built libmediasoupclient I got a lot errors. 

José mentioned in the other issue that libmediasoupclient has been tested on Windows. Is there any documentation about how to do it?

Thanks a lot!

**Comment by ibc** [comment]
It's been indeed built on Windows, but not by us. It may need some kind of kung-fu with Visual Studio and all that stuff we just have never used, so cannot help much :(

I'll close this issue because there is nothing we can add. If you get it working and want to contribute just write here how you got it and we'll document it.

Thanks.

**Comment by jmillan** [comment]
@Eldorado3, as @ibc says we have not tested in Windows ourselves. 

AFAIK, these are some flags to be set in your CMakeLists.txt:

```txt
target_compile_definitions(YourProyect PUBLIC
	$<$<PLATFORM_ID:Windows>:_WIN32_WINNT=0x0603>
	$<$<PLATFORM_ID:Windows>:WEBRTC_WIN>
	$<$<PLATFORM_ID:Windows>:NOMINMAX>
	$<$<PLATFORM_ID:Windows>:WIN32_LEAN_AND_MEAN>
	USE_BUILTIN_SW_CODECS
)

if (MSVC)
	target_link_libraries(YourProyect PRIVATE
		winmm
		Secur32
		wmcodecdspuuid
		msdmo
		dmoguids
		Strmiids
	)
```

I hope it helps

**Comment by Eldorado3** [comment]
@jmillan thanks a lot for the info, I'll give it a try. :)

**Comment by Eldorado3** [comment]
@jmillan I've successfully built libmediasoupclient on Windows with the suggested changes made to CMakeLists.txt. Thanks a ton! 👍

**Comment by jmillan** [comment]
Glad to hear that,

I'll keep this issue open until I document it later today.

**Comment by jmillan** [comment]
Hi @Eldorado3,

Not Windows users here. Could you maybe check and comment here what is each of those Windows libraries for? We would then add such comment to the doc for future users.

Thanks.

**Comment by Eldorado3** [comment]
@jmillan It seems that although the libmediasoupclient itself is built, I am still having problem to link it to an executable together with webrtc.lib. I need to spend more time to figure it out and will update later if succeeded.

**Comment by Eldorado3** [comment]
@jmillan Hi José,

I tested with different configurations and finally got it worked on Windows. 

The followings are what I set to build on Windows. WEBRTC_WIN is needed by webrtc.lib, NOMINMAX is to avoid any potential conflicts with std::min and std::max, WIN32_LEAN_AND_MEAN is to exclude unnecessary windows API files.

target_compile_definitions(YourProyect PUBLIC
	$<$<PLATFORM_ID:Windows>:WEBRTC_WIN>
	$<$<PLATFORM_ID:Windows>:NOMINMAX>
	$<$<PLATFORM_ID:Windows>:WIN32_LEAN_AND_MEAN>
)

if (MSVC)
	target_link_libraries(YourProyect PRIVATE
		winmm
		Secur32
		wmcodecdspuuid
		msdmo
		dmoguids
		Strmiids
                ${LIBWEBRTC_BINARY_PATH}/libwebrtc${CMAKE_STATIC_LIBRARY_SUFFIX}
	)

I also set the /MT flag to use the multithread, static version of the run-time library as the webrtc.lib by default use the static one

set(CMAKE_CXX_FLAGS_RELEASE "/MT")
set(CMAKE_CXX_FLAGS_DEBUG "/MTd")

Just my two cents.

**Comment by jmillan** [comment]
Thanks very much @Eldorado3

**Comment by hhhhqszka** [comment]
hi @Eldorado3 @jmillan , I've successfully built libmediasoupclient on Windows10 with vs2017 with your suggested changes made to CMakeLists.txt commented on 14 May 2019. Thanks a ton! 👍
But  i m still having only 3 errors  to link it to my project together with webrtc.lib.
all very similar errors like this:

**mediasoupclient.lib(Utils.obj)** : error LNK2019: **unresolved external symbol** 
class nlohmann::basic_json<class std::map, class std::vector, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char> >, 
	bool, 
	__int64, 
	unsigned __int64, 
	double, 
	class std::allocator, 
	struct nlohmann::adl_serializer> __cdecl sdptransform::parseParams(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char> > const &)
**referenced in function** 
void __cdecl mediasoupclient::Sdp::Utils::applyCodecParameters
(
	class nlohmann::basic_json<class std::map, class std::vector, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char> >, 
	bool,
	__int64, 
	unsigned __int64, 
	double, 
	class std::allocator, 
	struct nlohmann::adl_serializer> const &, 
	class nlohmann::basic_json<class std::map, class std::vector, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char> >, 
	bool,
	__int64, 
	unsigned __int64, 
	double, 
	class std::allocator, 
	struct nlohmann::adl_serializer> &
)

**Comment by hhhhqszka** [comment]
OK it's my fault, sdptransform.lib need to be added
