### ISSUE TITLE
Enable VP9 SVC and keep user given encoding.scalabilityMode

### ISSUE THREAD

**Issue by ibc** [versatica/libmediasoupclient#47]
Like [here](https://github.com/versatica/mediasoup-client/commit/e17c6b22ab02ebc4b10f24d1ea53bcc6ffc7d46a?ts=2). This is needed for letting the app set VP9 SVC available layers (at least for now).

However, the `webrtc::RtpEncodingParameters` struct does not have a `scalabilityMode` field so we have a problem. Perhaps we may have a derived class with it?

In the other side, in order to have VP9 SVC we should set the corresponding flag in webrtc. I assume it's something as follows (to be confirmed):

```c++
webrtc::field_trial::InitFieldTrialsFromString("WebRTC-SupportVP9SVC/EnabledByFlag_3SL3TL/");
```

**Comment by ibc** [comment]
BTW libmediasoupclient should also set the VP9 SVC trial flag.

**Comment by ibc** [comment]
Let's wait since libwebrtc will include support for per encoding `scalabilityMode` property "soon" (at least there is a working code done during the last hackathon).

**Comment by jmillan** [comment]
no such `scalabilityMode` in `webrtc::RtpEncodingParameters` as of today (m79)

**Comment by ibc** [comment]
It's supposed to be in 81 or more AFAIR.

**Comment by jmillan** [comment]
Already implemented. https://github.com/versatica/libmediasoupclient/pull/131
