### ISSUE TITLE
 error: no matching function for call to ‘rtc::Thread::Thread()’

### ISSUE THREAD

**Issue by jaygno** [versatica/libmediasoupclient#54]
arguments is not right.

**Comment by ibc** [comment]
I hope you will provide **much** more information and details or we can do nothing but just close this issue.

**Comment by jaygno** [comment]
` this->signalingThread.reset(new rtc::Thread());`
 the code in src/PeerConnection.cpp,  rtc::Thread request at least one argument.

**Comment by ibc** [comment]
Are you sure you are using libwebrtc M73?

**Comment by ibc** [comment]
Tested with libwebrtc `m73` branch. It works. So you are not using `m73` branch as the documentation clearly states. You neither replied to this question, so closing issue.
