### ISSUE TITLE
How to seperate the audio&video data of the diferent channel ?

### ISSUE THREAD

**Issue by huangjingpei** [versatica/libmediasoupclient#55]
I want to get some channels the YUV(for video ) and PCM (for audio)　data, But 
the peerconnection was created one only by libmediasoupclient , so I get the data by the function 
 in webrtc::AudioTrackSinkInterface OnData
class AudioTrackSinkInterface {
 public:
  virtual void OnData(const void* audio_data,
                      int bits_per_sample,
                      int sample_rate,
                      size_t number_of_channels,
                      size_t number_of_frames) = 0;

How to seperate the audio&video data of the diferent channel ?

**Comment by ibc** [comment]
Please, as the README says this is just for issues. Use the mediasoup Discourse Group for questions.

**Comment by huangjingpei** [comment]
I hold the one peerconnection , but I hold some consumers , I can't indentify the different consumer from the peerconnection,

**Comment by ibc** [comment]
mediasoup Discourse Group, please.
