### ISSUE TITLE
PeerConnection::Options not considered when selecting rtp parameters

### ISSUE THREAD

**Issue by Saku2** [versatica/libmediasoupclient#56]
At the moment the Device.extendedRtpParameters is calculated in Device::Load() which does not have access to custom PeerConnection::Options. PeerConnection::Options can e.g. limit available codecs, which at the moment causes libmediasoupclient to select an unsupported codec.

This could be fixed without breaking source compatibility by calculating these parameters in Device::CreateSendTransport/Device::CreateRecvTransport where required information is already present.

**Comment by ibc** [comment]
Which PeerConnection::Options may limit available codecs?

BTW I'm not against this change but it's not easy as it breaks current design (currently device extended capabilities need to be known **before** creating a transport and before creating producers or consumers on them.

**Comment by Saku2** [comment]
A custom encoder/decoder factory which supports limited number of codecs.

**Comment by ibc** [comment]
That makes sense. BTW how does the custom encoder tell the PeerConnection which codecs it supports?

**Comment by Saku2** [comment]
There's webrtc::Video<Encoder/Decoder>Factory::GetSupportedFormats() which will be implemented by the custom encoder/decoder.

**Comment by jmillan** [comment]
`Device::Load()` could simply have an optional [PeerConnection::Options](https://github.com/versatica/libmediasoupclient/blob/v3/include/PeerConnection.hpp#L105) argument so that the generated extendedRtpCapabilities are calcualted considering the provided encoder factories.

**Comment by ibc** [comment]
> `Device::Load()` could simply have an optional [PeerConnection::Options](https://github.com/versatica/libmediasoupclient/blob/v3/include/PeerConnection.hpp#L105) argument so that the generated extendedRtpCapabilities are calcualted considering the provided encoder factories.

I assume that, right now, we let the app pass its custom `PeerConnection::Options` (with a custom encoder for example) in `device.CreateXxxxTransport()`, is that right?

If so, it makes sense what you suggest: having `device.Load()` and optional `options` argument for passing a custom encoder and so on.

**Comment by ibc** [comment]
@Saku2 this should be implemented in #58 in the branch "device-Load-peerConnectionOptions". Can you take a look to it?

**Comment by ibc** [comment]
It's been merged into "v3" branch, so you can run just "git pull" and test.

**Comment by ibc** [comment]
Here the documentation: https://mediasoup.org/documentation/v3/libmediasoupclient/api/#device-Load
