### ISSUE TITLE
Issue receiving 3 Consumers

### ISSUE THREAD

**Issue by ibc** [versatica/libmediasoupclient#57]
As reported [here](https://mediasoup.discourse.group/t/failed-to-process-the-bundled-m-section/233) it seems that, when enabling more than 2 Consumers in a rev transport, libwebrtc does not like the SDP answer that it generates:

```
(channel.cc:264): Failed to connect to the new RtpTransport.
(peer_connection.cc:2148): Failed to set local answer sdp: Failed to process the bundled m= section.
[WARN] PeerConnection::OnFailure() | webtc::SetSessionDescriptionObserver failure [INTERNAL_ERROR:Failed to set local answer sdp: Failed to process the bundled m= section.]
```

SDP remote offer:

<details>

```
v=0
o=libmediasoupclient 10000 3 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-lite
a=fingerprint:sha-512 84:27:A4:28:A4:73:AF:43:02:2A:44:68:FF:2F:29:5C:3B:11:9A:60:F4:A8:F0:F5:AC:A0:E3:49:3E:B1:34:53:A9:85:CE:51:9B:ED:87:5E:B8:F4:8E:3D:FA:20:51:B8:96:EE:DA:56:DC:2F:5C:62:79:15:23:E0:21:82:2B:2C
a=msid-semantic: WMS *
a=group:BUNDLE 0 1 2
m=audio 7 UDP/TLS/RTP/SAVPF 100
c=IN IP4 127.0.0.1
a=rtpmap:100 opus/48000/2
a=fmtp:100 useinbandfec=1
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=setup:actpass
a=mid:0
a=sendonly
a=ice-ufrag:h3hk1iz6qqlnqlne
a=ice-pwd:yku5ej8nvfaor28lvtrabcx0wkrpkztz
a=candidate:udpcandidate 1 udp 1078862079 9.9.9.9 40533 typ host
a=candidate:udpcandidate 1 udp 1078862089 9:9:9:9:9:9 41333 typ host
a=end-of-candidates
a=ice-options:renomination
a=ssrc:1646727 cname:9WVRmmfpgF1IU5dm
a=ssrc:1646727 msid:9WVRmmfpgF1IU5dm 85QZdkmRxgql
a=rtcp-mux
a=rtcp-rsize
m=video 7 UDP/TLS/RTP/SAVPF 101 102
c=IN IP4 127.0.0.1
a=rtpmap:101 VP8/90000
a=rtpmap:102 rtx/90000
a=fmtp:101 x-google-start-bitrate=1500
a=fmtp:102 apt=101
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 nack sli
a=rtcp-fb:101 nack rpsi
a=rtcp-fb:101 nack app
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 goog-remb
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=setup:actpass
a=mid:1
a=sendonly
a=ice-ufrag:h3hk1iz6qqlnqlne
a=ice-pwd:yku5ej8nvfaor28lvtrabcx0wkrpkztz
a=candidate:udpcandidate 1 udp 1078862079 9.9.9.9 40533 typ host
a=candidate:udpcandidate 1 udp 1078862089 9:9:9:9:9:9 41333 typ host
a=end-of-candidates
a=ice-options:renomination
a=ssrc:2987398 cname:QvbXX7PTS5fIzGFq
a=ssrc:2987398 msid:QvbXX7PTS5fIzGFq f1oe7o5kNY5w
a=ssrc:3356717 cname:QvbXX7PTS5fIzGFq
a=ssrc:3356717 msid:QvbXX7PTS5fIzGFq f1oe7o5kNY5w
a=ssrc-group:FID 2987398 3356717
a=rtcp-mux
a=rtcp-rsize
m=audio 7 UDP/TLS/RTP/SAVPF 100
c=IN IP4 127.0.0.1
a=rtpmap:100 opus/48000/2
a=fmtp:100 useinbandfec=1
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=setup:actpass
a=mid:2
a=sendonly
a=ice-ufrag:h3hk1iz6qqlnqlne
a=ice-pwd:yku5ej8nvfaor28lvtrabcx0wkrpkztz
a=candidate:udpcandidate 1 udp 1078862079 9.9.9.9 40533 typ host
a=candidate:udpcandidate 1 udp 1078862089 9:9:9:9:9:9 41333 typ host
a=end-of-candidates
a=ice-options:renomination
a=ssrc:1646727 cname:9WVRmmfpgF1IU5dm
a=ssrc:1646727 msid:9WVRmmfpgF1IU5dm 85QZdkmRxgql
a=rtcp-mux
a=rtcp-rsize
```

</details>

SDP local answer:

<details>

```
v=0
o=- 3924721801030217082 4 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic:  WMS
a=group:BUNDLE 0 1 2
m=audio 55662 UDP/TLS/RTP/SAVPF 100
c=IN IP4 192.168.1.35
a=rtpmap:100 opus/48000/2
a=fmtp:100 minptime=10;useinbandfec=1
a=rtcp:9 IN IP4 0.0.0.0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=setup:active
a=mid:0
a=recvonly
a=ice-ufrag:k7Nn
a=ice-pwd:9SPT2m21bSoWgMY21rdg6xlb
a=fingerprint:sha-256 CD:73:5E:4B:93:87:1C:8A:6C:76:3B:8C:DB:A9:B8:8D:11:16:C2:37:96:56:F8:C7:9D:79:DC:53:0F:B2:5A:DC
a=candidate:3188989370 1 udp 2122260223 192.168.1.35 55662 typ host generation 0 network-id 1 network-cost 50
a=candidate:671757166 1 udp 2122194687 5.5.5.5 58009 typ host generation 0 network-id 2 network-cost 50
a=ice-options:trickle
a=rtcp-mux
m=video 9 UDP/TLS/RTP/SAVPF 101 102
c=IN IP4 0.0.0.0
a=rtpmap:101 VP8/90000
a=rtpmap:102 rtx/90000
a=fmtp:102 apt=101
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:101 goog-remb
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=setup:active
a=mid:1
a=recvonly
a=ice-ufrag:k7Nn
a=ice-pwd:9SPT2m21bSoWgMY21rdg6xlb
a=fingerprint:sha-256 CD:73:5E:4B:93:87:1C:8A:6C:76:3B:8C:DB:A9:B8:8D:11:16:C2:37:96:56:F8:C7:9D:79:DC:53:0F:B2:5A:DC
a=ice-options:trickle
a=rtcp-mux
a=rtcp-rsize
m=audio 9 UDP/TLS/RTP/SAVPF 100
c=IN IP4 0.0.0.0
a=rtpmap:100 opus/48000/2
a=fmtp:100 minptime=10;useinbandfec=1
a=rtcp:9 IN IP4 0.0.0.0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=setup:active
a=mid:2
a=recvonly
a=ice-ufrag:k7Nn
a=ice-pwd:9SPT2m21bSoWgMY21rdg6xlb
a=fingerprint:sha-256 CD:73:5E:4B:93:87:1C:8A:6C:76:3B:8C:DB:A9:B8:8D:11:16:C2:37:96:56:F8:C7:9D:79:DC:53:0F:B2:5A:DC
a=ice-options:trickle
a=rtcp-mux
```

</details>

**Comment by ibc** [comment]
Confirmed that we are properly enabling Unified-Plan in libmediasoupclient. Otherwise, if we change this:

```c++
config.sdp_semantics = webrtc::SdpSemantics::kUnifiedPlan;
```

to this:

```c++
config.sdp_semantics = webrtc::SdpSemantics::kPlanB;
```

we get this obvious error:

```
# Fatal error in: ../../pc/peer_connection.cc, line 1432
# last system error: 38
# Check failed: IsUnifiedPlan()
# AddTransceiver is only available with Unified Plan SdpSemantics
```

**Comment by ibc** [comment]
Ok, so the problem I see in the logs is this one:

```
(rtp_stream_receiver_controller.cc:25): RtpStreamReceiverController::Receiver::Receiver: Sink could not be added for SSRC=1000008.
```

I think that this is related to the default builtin "audio handler" that may be does not allow passing two remote tracks. @jmillan thoughts? may be the tests should use a fake/noop audio handler?

However the same happens if, instead of a second audio consumer, we add a second video consumer:

```
(rtp_stream_receiver_controller.cc:25): RtpStreamReceiverController::Receiver::Receiver: Sink could not be added for SSRC=2000001.
(rtp_stream_receiver_controller.cc:25): RtpStreamReceiverController::Receiver::Receiver: Sink could not be added for SSRC=3000001.
(call.cc:1223): Attempting to sync more than one audio/video pair within the same sync group. This is not supported in the current implementation.
```

**Comment by jmillan** [comment]
> may be the tests should use a fake/noop audio handler?

Definitely the test should not rely on a specific handler so it should use a fake one.

**Comment by ibc** [comment]
Unfortunately using a `test/AudioDeviceDummy.hpp` does not fix the issue:

https://github.com/versatica/libmediasoupclient/commit/dc1ebf86976564a63cf98c0672427a9fc2dd1227?ts=2

**Comment by ibc** [comment]
We should check this [project](https://github.com/mpromonet/webrtc-streamer/blob/master/src/main.cpp) and how it uses `webrtc::AudioDeviceModule::kDummyAudio` (not sure if 100% related).

**Comment by ibc** [comment]
BTW libwebrtc provides a `FakeAudioDeviceModule` in `modules/audio_device/include/fake_audio_device.h`:

```c++
rtc::scoped_refptr<webrtc::AudioDeviceModule> audioDeviceModule(
		new webrtc::FakeAudioDeviceModule());
```

**Comment by ibc** [comment]
Ohhh, this is the remote SDP offer generated by libmediasoupclient. It has 2 `m=audio` sections that are equal! I mean: they have the very same `a=ssrc` lines!!!

```
REMOTE OFFER


v=0
o=libmediasoupclient 10000 3 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-lite
a=fingerprint:sha-512 84:27:A4:28:A4:73:AF:43:02:2A:44:68:FF:2F:29:5C:3B:11:9A:60:F4:A8:F0:F5:AC:A0:E3:49:3E:B1:34:53:A9:85:CE:51:9B:ED:87:5E:B8:F4:8E:3D:FA:20:51:B8:96:EE:DA:56:DC:2F:5C:62:79:15:23:E0:21:82:2B:2C
a=msid-semantic: WMS *
a=group:BUNDLE 0 1 2

m=audio 7 UDP/TLS/RTP/SAVPF 100
c=IN IP4 127.0.0.1
a=rtpmap:100 opus/48000/2
a=fmtp:100 useinbandfec=1
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=setup:actpass
a=mid:0
a=sendonly
a=ice-ufrag:h3hk1iz6qqlnqlne
a=ice-pwd:yku5ej8nvfaor28lvtrabcx0wkrpkztz
a=candidate:udpcandidate 1 udp 1078862079 9.9.9.9 40533 typ host
a=candidate:udpcandidate 1 udp 1078862089 9:9:9:9:9:9 41333 typ host
a=end-of-candidates
a=ice-options:renomination
a=ssrc:1646727 cname:9WVRmmfpgF1IU5dm
a=ssrc:1646727 msid:9WVRmmfpgF1IU5dm 85QZdkmRxgql
a=rtcp-mux
a=rtcp-rsize

m=video 7 UDP/TLS/RTP/SAVPF 101 102
c=IN IP4 127.0.0.1
a=rtpmap:101 VP8/90000
a=rtpmap:102 rtx/90000
a=fmtp:101 x-google-start-bitrate=1500
a=fmtp:102 apt=101
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 nack sli
a=rtcp-fb:101 nack rpsi
a=rtcp-fb:101 nack app
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 goog-remb
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=setup:actpass
a=mid:1
a=sendonly
a=ice-ufrag:h3hk1iz6qqlnqlne
a=ice-pwd:yku5ej8nvfaor28lvtrabcx0wkrpkztz
a=candidate:udpcandidate 1 udp 1078862079 9.9.9.9 40533 typ host
a=candidate:udpcandidate 1 udp 1078862089 9:9:9:9:9:9 41333 typ host
a=end-of-candidates
a=ice-options:renomination
a=ssrc:2987398 cname:QvbXX7PTS5fIzGFq
a=ssrc:2987398 msid:QvbXX7PTS5fIzGFq f1oe7o5kNY5w
a=ssrc:3356717 cname:QvbXX7PTS5fIzGFq
a=ssrc:3356717 msid:QvbXX7PTS5fIzGFq f1oe7o5kNY5w
a=ssrc-group:FID 2987398 3356717
a=rtcp-mux
a=rtcp-rsize

m=audio 7 UDP/TLS/RTP/SAVPF 100
c=IN IP4 127.0.0.1
a=rtpmap:100 opus/48000/2
a=fmtp:100 useinbandfec=1
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=setup:actpass
a=mid:2
a=sendonly
a=ice-ufrag:h3hk1iz6qqlnqlne
a=ice-pwd:yku5ej8nvfaor28lvtrabcx0wkrpkztz
a=candidate:udpcandidate 1 udp 1078862079 9.9.9.9 40533 typ host
a=candidate:udpcandidate 1 udp 1078862089 9:9:9:9:9:9 41333 typ host
a=end-of-candidates
a=ice-options:renomination
a=ssrc:1646727 cname:9WVRmmfpgF1IU5dm
a=ssrc:1646727 msid:9WVRmmfpgF1IU5dm 85QZdkmRxgql
a=rtcp-mux
a=rtcp-rsize
```

**Comment by ibc** [comment]
And it was because it was using the same `audioConsumerRemoteParameters`.... stupid bug in the test unit. Work in progress.

**Comment by ibc** [comment]
And this is fixed. The test unit was wrong (it was setting the very same consumer RTP parameters for second audio consumer, so same SSRC, CNAME, track.id, etc was being used. Now fixed.

There is no issue at all.

**Comment by ibc** [comment]
Let's reopen it since it seems that the issue still happens (as reported [here](https://mediasoup.discourse.group/t/failed-to-process-the-bundled-m-section/233/17)) when receiving creating consumers with the following parameters:

```
1:
recv msg:{“request”:true,“id”:5242967,“method”:“newConsumer”,“data”:{“peerId”:“ug1vefaw”,“producerId”:“1230cb96-9b94-4fd2-8534-43ba6c56051e”,“id”:“49bd38d9-4938-4552-a7ff-6e2523d122d9”,“kind”:“audio”,“rtpParameters”:{“codecs”:[{“mimeType”:“audio/opus”,“clockRate”:48000,“payloadType”:100,“channels”:2,“rtcpFeedback”:[],“parameters”:{“minptime”:10,“useinbandfec”:1,“sprop-stereo”:1,“usedtx”:1}}],“headerExtensions”:[{“uri”:“http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time",“id”:4},{“uri”:“urn:ietf:params:rtp-hdrext:ssrc-audio-level”,“id”:10}],“encodings”:[{“ssrc”:994350334}],“rtcp”:{“cname”:“twlICLiNTiYySQwG”,“reducedSize”:true,“mux”:true}},“type”:“simple”,“appData”:{“peerId”:“ug1vefaw”},"producerPaused”:false}}

2:
recv msg:{“request”:true,“id”:8524214,“method”:“newConsumer”,“data”:{“peerId”:“ug1vefaw”,“producerId”:“15ad635c-1829-461f-9690-083f173716cb”,“id”:“18d413d8-e916-4a40-9eb2-5b3af0e937c6”,“kind”:“video”,“rtpParameters”:{“codecs”:[{“mimeType”:“video/VP8”,“clockRate”:90000,“payloadType”:101,“rtcpFeedback”:[{“type”:“goog-remb”},{“parameter”:“fir”,“type”:“ccm”},{“type”:“nack”},{“parameter”:“pli”,“type”:“nack”}],“parameters”:{}},{“mimeType”:“video/rtx”,“clockRate”:90000,“payloadType”:102,“rtcpFeedback”:[],“parameters”:{“apt”:101}}],“headerExtensions”:[{“uri”:“http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time",“id”:4},{“uri”:“http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07”,“id”:6},{“uri”:“urn:3gpp:video-orientation”,“id”:11},{“uri”:“urn:ietf:params:rtp-hdrext:toffset”,“id”:12}],“encodings”:[{“ssrc”:869916720,“rtx”:{“ssrc”:998007240},“scalabilityMode”:“S3T3”}],“rtcp”:{“cname”:“twlICLiNTiYySQwG”,“reducedSize”:true,“mux”:true}},“type”:“simulcast”,“appData”:{“peerId”:“ug1vefaw”},"producerPaused”:false}}

3:
recv msg:{“request”:true,“id”:36081,“method”:“newConsumer”,“data”:{“peerId”:“tk804bas”,“producerId”:“84545906-fc9d-47de-830a-e81d7a52b784”,“id”:“56a18acc-138b-49a5-925b-a12ab37e3dca”,“kind”:“audio”,“rtpParameters”:{“codecs”:[{“mimeType”:“audio/opus”,“clockRate”:48000,“payloadType”:100,“channels”:2,“rtcpFeedback”:[],“parameters”:{“minptime”:10,“useinbandfec”:1,“sprop-stereo”:1,“usedtx”:1}}],“headerExtensions”:[{“uri”:“http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time",“id”:4},{“uri”:“urn:ietf:params:rtp-hdrext:ssrc-audio-level”,“id”:10}],“encodings”:[{“ssrc”:848431512}],“rtcp”:{“cname”:“fj/HX2plkrsO7yKt”,“reducedSize”:true,“mux”:true}},“type”:“simple”,“appData”:{“peerId”:“tk804bas”},"producerPaused”:false}}
```

**Comment by ibc** [comment]
BTW huangjingpei, may I know what are those numeric `ids` you get? Why are they numeric (5242967, 8524214, 36081) instead of UUIDv4 string values as those generated in `consumer.id` in server side?

**Comment by huangjingpei** [comment]
I made some tests about 30+ times with v3demo.mediasoup.org server.  and I have not found some errors yet. 
I will test more times again.

**Comment by ibc** [comment]
Where did you testing before when you encountered the issue? In a local demo? same as the mediasoup-demo? or did you modify it somehow?

**Comment by huangjingpei** [comment]
YES , I run it in a local demo from https://github.com/versatica/mediasoup-demo.git,and I run it by README.md

Commit 1812de8d19df704a22c379f48e91a24f522f3560 (HEAD -> master, origin/v3, v3)
Author: Iñaki Baz Castillo <ibc@aliax.net>
Date:   Tue Jul 23 22:35:27 2019 +0200,

**Comment by ibc** [comment]
If it does never happen with the official mediasoup-demo when consuming more than 2 remote producers in you libmediasoupclient based app, then I'd say that there is no issue. There is no reason to just fail in your local deployment of the demo (unless you have changed something and such a change produces a buggy behavior somewhere).

Can you share your libmediasoupclient based app to test it against the demo?

**Comment by huangjingpei** [comment]
I wanna to share the source code ,but the code depends libraries  boost , webrtc m74 branch  and etc. 

I can show main source code:

<details>

#include <iostream>
#include <string>

#include "RoomClient.hpp"
#include "Utils.hpp"

using json = nlohmann::json;

class map_value_finder
{
public:
       map_value_finder(const std::string &cmp_string):object(cmp_string){}
       bool operator ()(const std::map<int, std::string>::value_type &pair)
       {
            return pair.second == object;
       }
private:
        const std::string &object;
};

#define RandomInt32 (mediasoupclient::Utils::getRandomInteger(1000009, 9999999))
RoomClient::RoomClient() {
	record_instance_ = RecordInstance::GetInstance();
	wss_client_.reset(WssClient::Create());
	system("rm -rf out.mp4");
	record_instance_->StartRecord("out.mp4");
	wss_state_ = wss_none;
	recv_transport_ = NULL;
	record_idx_ = 1;
}

RoomClient::~RoomClient() {

}

bool RoomClient::RunAndWaitForever(std::string wss) {
	wss_client_->setEventListener(this);
	wss_client_->StartAndRun(wss);
	return true;
}

void RoomClient::onOpen() {
	GetRouterRtpCapabilities();
}

void RoomClient::GetRouterRtpCapabilities() {
	json body = { { "request", true }, { "id", RandomInt32 }, { "method",
			"getRouterRtpCapabilities" }, { "data", { } } };

	wss_client_->Send(body.dump());
	wss_state_ = wss_getRouterRtpCapabilities;
}

void RoomClient::CreateWebRtcTransport() {
	json body = { { "request", true }, { "id", RandomInt32 }, { "method",
			"createWebRtcTransport" }, { "data", { { "forceTcp", false }, {
			"producing", false }, { "consuming", true }, { "sctpCapabilities", {
			"numStreams", { { "OS", 1024 }, { "MIS", 1024 } } } } } } };

	printf("send %s:%s\n", __FUNCTION__, body.dump().c_str());
	wss_client_->Send(body.dump());
	wss_state_ = wss_createWebRtcTransport;
}

void RoomClient::Join(nlohmann::json createWebRtcTransportResponse) {
	if (createWebRtcTransportResponse.find("id")
			== createWebRtcTransportResponse.end()) {
		std::cout << "'id' missing in response" << std::endl;
		return;
	} else if (createWebRtcTransportResponse.find("iceParameters")
			== createWebRtcTransportResponse.end()) {
		std::cout << "'iceParametersd' missing in response" << std::endl;

		return;
	} else if (createWebRtcTransportResponse.find("iceCandidates")
			== createWebRtcTransportResponse.end()) {
		std::cout << "'iceCandidates' missing in response" << std::endl;

		return;
	} else if (createWebRtcTransportResponse.find("dtlsParameters")
			== createWebRtcTransportResponse.end()) {
		std::cout << "'dtlsParameters' missing in response" << std::endl;
		return;
	}

	std::cout << ">>> creating recv transport..." << std::endl;

	this->transport_uuid_ = createWebRtcTransportResponse["id"];

	recv_transport_ = this->device.CreateRecvTransport(
			this,
			this->transport_uuid_,
			createWebRtcTransportResponse["iceParameters"],
			createWebRtcTransportResponse["iceCandidates"],
			createWebRtcTransportResponse["dtlsParameters"]);

	json body = {
			{ "request", true },
			{ "id", RandomInt32 },
			{ "method", "join" },
			{ "data", {
					{ "displayName", "RSU" },
					{ "device", {
							{ "flag", "unknown" },
							{ "name", "Chrome" },
							{"version", "75.0.3770.100" }
					},

			} } }

	};
	body["data"]["rtpCapabilities"] = this->device.GetRtpCapabilities();
	printf("send %s:%s\n", __FUNCTION__, body.dump().c_str());

	wss_client_->Send(body.dump());
	wss_state_ = wss_join;

}

void RoomClient::ConnectWebRtcTransport(nlohmann::json dtlsParameters) {
	json body = {
			{ "request", true },
			{ "id", RandomInt32 },
			{ "method","connectWebRtcTransport" },
			{ "data", {
					{ "transportId",transport_uuid_ },


			} } };
	body["data"]["dtlsParameters"] = dtlsParameters;
	wss_client_->Send(body.dump());

}

void RoomClient::ProcessPeers(nlohmann::json peers) {
	for (int i = 0; i < peers.size(); i++) {
		ProcessNewPeer(peers[i]);
	}
	wss_state_ == wss_working_;
}

void RoomClient::ProcessNewPeer(nlohmann::json peer) {
	printf("ProcessNewPeer !\n");
	struct Participant participant;
	participant.displayName = peer["displayName"].get<std::string>();
	participant.peerId = peer["id"].get<std::string>();
	participant.idx = record_idx_;
	participants_.push_back(participant);
	record_instance_->AddParticipant(record_idx_);
	record_instance_->SetCompositionType(participants_.size());
	++record_idx_;
}

void RoomClient::PorcessNewConsumer(nlohmann::json newConsumer, int msgId) {
	if (newConsumer.find("id")
			== newConsumer.end()) {
		std::cout << "'id' missing in response" << std::endl;
		return;
	} else if (newConsumer.find("producerId")
			== newConsumer.end()) {
		std::cout << "'iceParametersd' missing in response" << std::endl;

		return;
	} else if (newConsumer.find("kind")
			== newConsumer.end()) {
		std::cout << "'iceCandidates' missing in response" << std::endl;

		return;
	} else if (newConsumer.find("rtpParameters")
			== newConsumer.end()) {
		std::cout << "'dtlsParameters' missing in response" << std::endl;
		return;
	}
	std::string peerId = newConsumer["peerId"].get<std::string>();

	std::list<struct Participant>::iterator iter;
//	struct Participant participant;
//	participant.setPeerId(peerId);
//	iter = std::find(participants_.begin(), participants_.end(), participant);
	int channel;
	iter = std::find_if(participants_.begin(), participants_.end(),
            [&peerId](decltype(*(participants_.begin())) & vt){
        return (strcmp(vt.peerId.c_str(), peerId.c_str()) ==0);
    });
	if (iter != participants_.end()) {
		channel = iter->idx;
	} else {
		std::cout << "can not find the peer information" << " : peerId " << peerId.c_str() << std::endl;
		return ;
	}
	recv_transport_->Consume(/*channel,
			this,*/
			this,
			newConsumer["id"],
			newConsumer["producerId"],
			newConsumer["kind"],
			&newConsumer["rtpParameters"]);


	SendConsumeReponse(msgId);
	recv_transports_.insert(std::map<std::string, mediasoupclient::RecvTransport*>::value_type(newConsumer["peerId"].get<std::string>(), recv_transport_));

}

void RoomClient::PeerClosed(std::string peerId) {
	printf("PEERCLOSED!　peerId　\n", peerId.c_str());
	std::list<struct Participant>::iterator it;
//	struct Participant participant;
//	participant.setPeerId(peerId);
//	iter = std::find(participants_.begin(), participants_.end(), participant);
	int channel;
	it = std::find_if(participants_.begin(), participants_.end(),
            [&peerId](decltype(*(participants_.begin())) & vt){
        return (strcmp(vt.peerId.c_str(), peerId.c_str()) ==0);
    });

	if (it != participants_.end()) {
		channel = it->idx;
		participants_.erase(it);
		record_instance_->RemoveParticipant(channel);
	}


	std::map<std::string, mediasoupclient::RecvTransport*>::iterator iter;
	iter = recv_transports_.find(peerId);

	if (iter != recv_transports_.end()) {
		recv_transports_.erase(iter);
		iter->second->Close();
	} else {
		//input argument error　!!!
	}
	record_instance_->SetCompositionType(recv_transports_.size());

	printf("recv_transports_ size %lz\n", recv_transports_.size());
	if (recv_transports_.size() <=0) {
		record_instance_->StopRecord();
	}
}

void RoomClient::SendConsumeReponse(int id)
{
	json body =
	{
			{ "response", true },
			{ "id", id },
			{ "ok","true" },
			{ "data", "{}"}
	};
	printf("SendConsumeReponse %s\n", body.dump().c_str());
	wss_client_->Send(body.dump());

}
void RoomClient::onMessage(std::string msg) {
	printf("recv msg:%s\n", msg.c_str());
	auto r = json::parse(msg);
//	auto it = r.find("id");
//	if (it == r.end()) {
//		return;
//	}
	printf("wss_state_ %d\n", wss_state_);
	auto resp = r.find("response");
	auto resq = r.find("request");
	auto notification = r.find("notification");
	if (resp != r.end()) {
		auto method = r.find("method");
		if (method != r.end()) {
		}
		if (wss_state_ == wss_getRouterRtpCapabilities) {
			auto routerRtpCapabilitiesResponse = nlohmann::json::parse(msg);
			auto routerRtpCapabilities = routerRtpCapabilitiesResponse["data"];
			this->device.Load(routerRtpCapabilities);
			CreateWebRtcTransport();
			return;
		} else if (wss_state_ == wss_createWebRtcTransport) {
			auto createWebRtcTransportResponse = nlohmann::json::parse(msg);
			Join(createWebRtcTransportResponse["data"]);
			return;
		} else if (wss_state_ == wss_join) {
			auto joinResponse = nlohmann::json::parse(msg);
			auto peers = joinResponse["data"]["peers"];
			if (peers.is_array()) {
				ProcessPeers(peers);
			}
			wss_state_ == wss_working_;
			return;
		} else if (wss_state_ == wss_working_) {
			return;

		}
		if (*resp == "createWebRtcTransport") {

		}
	} else if (resq != r.end()){
		auto response = nlohmann::json::parse(msg);
		auto method = response["method"];
		printf("method.dump().c_str() %s\n", method.dump().c_str());
		if (method.get<std::string>() == "newConsumer") {
			PorcessNewConsumer(response["data"], response["id"].get<int>());
			return;

		}
	} else if (notification != r.end()) {
		auto response = nlohmann::json::parse(msg);
		auto method = response["method"];
		if (method.get<std::string>() == "peerClosed") {
			PeerClosed(response["data"]["peerId"].get<std::string>());
		} else if (method.get<std::string>() == "newPeer") {
			auto peer = response["data"];
			ProcessNewPeer(peer);
		}

	}
}

void RoomClient::OnTransportClose(mediasoupclient::Consumer *consumer) {
	std::cout << "OnTransportClose" << std::endl;
}

std::future<void> RoomClient::OnConnect(mediasoupclient::Transport *transport,
		const nlohmann::json &dtlsParameters) {
	std::cout << "OnConnect" << dtlsParameters.dump().c_str() << std::endl;
	std::promise<void> promise;
	//FixMe send connectWebRtcTransport???
	ConnectWebRtcTransport(dtlsParameters);
	promise.set_value();

	return promise.get_future();
}
void RoomClient::OnConnectionStateChange(mediasoupclient::Transport *transport,
		const std::string &connectionState) {
	std::cout << "OnConnectionStateChange: connectionState: " << connectionState
			<< std::endl;

}

</details>

**Comment by ibc** [comment]
Have you been able to reproduce the issue in the online mediasoup-demo?

**Comment by huangjingpei** [comment]
I use v3demo as the server, there is no problem with the test.
Then I set up the mediasoup-demo server test on a new machine and found no problems.
And then, I tested it on my machine again, mediasoup-demo is also running on this machine, the problem still exists.

So is it caused by the browser, mediasoupclient client and server on the same computer when I tested it?
I look forward to your answer, thank you!

**Comment by ibc** [comment]
Let's focus on the only difference we see at this moment, which is the fact that it just fails for you in localhost. I assume you use the mediasoup-demo server and app unmodified in localhost.

Please, do this:

* Make a fresh install in localhost of the mediasoup-demo.

* Reproduce the problem with libmediasoupclient (the third Consumer fails).

* Then modify this [line](https://github.com/versatica/mediasoup-demo/blob/v3/server/lib/Room.js#L1419) and set:

```js
paused : true
```

* And comment this [line](https://github.com/versatica/mediasoup-demo/blob/v3/server/lib/Room.js#L1500) and the next one.

* And try again and let's know if it fails again or not.

**Comment by huangjingpei** [comment]
Modify it as you told it, then test it many times, no crash happens again, Is this a solution to the problem? could you tell me what is the reason?

**Comment by ibc** [comment]
Please confirm that it fails in localhost without the modification and it never fails with the modification. Be as explicit as possible. Then we'll theorize.

**Comment by huangjingpei** [comment]
I tested that there would be an abnormal crash about every 7 times before the modification.

After the modification,  I ran a total of more than 100 times and the program still did not terminate abnormally.

**Comment by ibc** [comment]
So it may happen that, in localhost, RTP audio packets were reaching the PeerConnection in libmediasoupclient **before** the SDP O/A terminates so those RTP packets (and their SSRC) were wrongly associated to a previous m=audio section and, later, then the new Consumer was created and its SDP O/A attempted, it failed because such a SSRC was already assigned to a different m=audio section.

I've seen that problem reported in the past in general WebRTC usage (even in browser). This week I'll modify the mediasoup-demo and will document this.

**Comment by ibc** [comment]
The mediasoup-demo has been updated to always create server side consumers in paused mode and resume them once the remote client acknowledges that it's ready to receive the new RTP packets.

It has also been properly documented in the API documentation.

In addition, it has been announced in the mediasoup Discourse Group: https://mediasoup.discourse.group/t/create-server-side-consumers-with-paused-true/244

So thanks for reporting and for all the tests you have done. Let's close this :)
