### ISSUE TITLE
crash when profile-level-id=640032

### ISSUE THREAD

**Issue by penguinol** [versatica/libmediasoupclient#60]
It seems libsdptransform::parseParams decodes profile-level-id 640032 as integer but 4d0032 as string.
And  Utils::extractRtpCapabilities does not do any special handling for this.
It will crash at `aParameters["profile-level-id"] = aCodec["parameters"]["profile-level-id"].get<std::string>();`  when calling ortc::matchCodecs

**Comment by jmillan** [comment]
Fixed, thanks for reporting @penguinol!
