### ISSUE TITLE
Reuse SDP m= sections for sending media

### ISSUE THREAD

**Issue by ibc** [versatica/libmediasoupclient#61]
Instead of disabling (by setting `a=inactive`) sending transceivers, close them with remote m= port 0 to later reuse it when creating a new sending transceiver (via `pc.addTransceiver()`).

* [Related commit in mediasoup-client](https://github.com/versatica/mediasoup-client/commit/6a5fcbeb6af91919f88e1f5d24301e9792b6f5be?ts=2)
* [Related issue in libwebrtc](https://bugs.chromium.org/p/webrtc/issues/detail?id=10864)

**Comment by jmillan** [comment]
Done b219aa51da32c07742ee4ca86a71245e88d60012
