### ISSUE TITLE
Add `additionalSettings` in transport creation API

### ISSUE THREAD

**Issue by ibc** [versatica/libmediasoupclient#65]
As done in mediasoup-client v3 [here](https://github.com/versatica/mediasoup-client/commit/7dd6a2b61ff6ff9596d94a286118e21f24e2a3d5).

Also add documentation to libmediasoupclient API as [here](https://github.com/versatica/mediasoup-website/commit/7203b867c9870156a1817e80672f0da2aaa63155).

**Comment by jmillan** [comment]
in `libmediasoupclient`  `webrtc::PeerConnectionInterface::RTCConfiguration` is used for transport creation which includes all possible settings supported by `libwebrtc`.
