### ISSUE TITLE
Confused about MSC_LOG_TRACE

### ISSUE THREAD

**Issue by haiyangwu** [versatica/libmediasoupclient#66]
As referenced below,  why `MSC_LOG_TRACE` hash a check `Logger::logLevel == Logger::LogLevel::LOG_DEBUG` instead of `Logger::logLevel == Logger::LogLevel:: LOG_TRACE ` ? Is it on purpose or just a typo ?

https://github.com/versatica/libmediasoupclient/blob/0b8cfca19b59d92d38c15ce144adfb3e842d1bcb/include/Logger.hpp#L115

**Comment by ibc** [comment]
Hi, it's on purpose and it's documented:

https://mediasoup.org/documentation/v3/libmediasoupclient/api/#Logger

so trace logs are just shown when log level is set to debug.
