### ISSUE TITLE
Make producer.replacetrack() ignore if same track given

### ISSUE THREAD

**Issue by ibc** [versatica/libmediasoupclient#67]
As [here](https://github.com/versatica/mediasoup-client/commit/9c849d04f27a5dc07c74f4892f857c11f9b027a3#diff-be1b785c6c97be8edb2e3856884ccaa5R182).

And document it in the website (same as done for mediasoup-client in `produce.replaceTrack()` method).

**Comment by ibc** [comment]
Done in `v3` branch.

**Comment by jmillan** [comment]
already done
