### ISSUE TITLE
crash when processing some special profile-level-id

### ISSUE THREAD

**Issue by penguinol** [versatica/libmediasoupclient#68]
The library can not processing profile-level-id 42e034 correctly.
42e034 will be decoded as 42*10^34, and std::to_string can not convert it back to 42e034.
Maybe we should fix it in libsdptransform

This bug is similar to #60

**Comment by ibc** [comment]
Should be fixed in 3.0.8 GIT tag. Thanks for reporting.

**Comment by jessonliu** [comment]
I ran into this problem before and changed the code! It seems that the author has solved the problem now! I need to update it too!
