### ISSUE TITLE
Delete codec.channels if video

### ISSUE THREAD

**Issue by ibc** [versatica/libmediasoupclient#76]
Please @jmillan, apply [this commit](https://github.com/versatica/mediasoup-client/commit/3d34f2643ea578d635898b4f7144bf518c7dad7e?ts=2) into libmediasoupclient. It fixes a regression due to recent changes that is causing several issues when people tries to interoperate with mediasoup.

**Comment by jmillan** [comment]
done 420cc7b5dcf8e8999196bce125ee4a4d751d1db3
