### ISSUE TITLE
Bug about range of uniform_int_distribution ?

### ISSUE THREAD

**Issue by haiyangwu** [versatica/libmediasoupclient#79]
https://github.com/versatica/libmediasoupclient/blob/e91e83876f00779599772b26015e2e5c520fda54/include/Utils.hpp#L68

The comment means the range is `[min, max)`

but according to [Produces random integer values i, uniformly distributed on the closed interval [a, b]](https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution), the range is `[min, max]`

On Android,  it will reach the max then the function `getRandomString` in `utils.hpp` will be wrong, eg `\u0000jk4CjwjiJCX`

**Comment by ibc** [comment]
Do you mean that it should be this instead?:

```c++
- std::uniform_int_distribution<std::string::size_type> dis(0, chars.size());
+ std::uniform_int_distribution<std::string::size_type> dis(0, chars.size() - 1);
```

**Comment by haiyangwu** [comment]
@ibc  Yes, I've changed in my local build for android, but not sure about other platforms.

**Comment by ibc** [comment]
I don't think this is platform dependant. This is a clear bug. @jmillan ?

**Comment by ibc** [comment]
I've fixed it in "v3" branch.

**Comment by jmillan** [comment]
Yeah, it's correct 👍
