### ISSUE TITLE
VideoSinkInterface::OnFrame() does not been called when I was trying consume a video stream.

### ISSUE THREAD

**Issue by sltruman** [versatica/libmediasoupclient#81]
![image](https://user-images.githubusercontent.com/12881971/80507212-30d58780-89a9-11ea-8de8-3cadd763d318.png)

**Comment by ibc** [comment]
Please, do not report screenshots. Also, we do nothing with VideoSinkInterface. That's libwebrtc business.

**Comment by jmillan** [comment]
How does this relate to libmediasoupclient?

If you have a libwebrtc specific question please ask in the corresponding mailing list or bug tracker. libmediasoupclient does not handle that.

For libmediasoupclient specific questions use the discourse group.

**Comment by sltruman** [comment]
> Please, do not report screenshots. Also, we do nothing with VideoSinkInterface. That's libwebrtc business.

you are right and I found that just was coding mistake.
