### ISSUE TITLE
fake_audio_capture_module.o not exists in the libwebrtc m79 branch

### ISSUE THREAD

**Issue by xiawenq** [versatica/libmediasoupclient#82]
Hi Everyon,

when i follow the document [libmediasoupclient v3 Installation](https://mediasoup.org/documentation/v3/libmediasoupclient/installation/),  Create the C++ libraryes,    there is good to compiled libwebrtc project. But I got a error message when build the libmediasoupclient cmake project, It say fake_audio_capture_module.o can't be found. Actually the ${LIBWEBRTC_BINARY_PATH}/pc/pc_test_utils/fake_audio_capture_module.o not be exists. 

sorry, maybe I report the issue to another repo such like libwebrtc or google, But I don't know how to report. So you don't have that problem, do you?

the compile everiment:
system info: docker instance based ubuntu18.0.4
cmake version: 3.16.3
gcc version: gcc-6.3.0
libwebrtc version: m79, compile command: ```gn gen out/mybuild-m79 --args='is_debug=false is_component_build=false is_clang=false rtc_include_tests=false rtc_use_h264=true rtc_enable_protobuf=false use_rtti=true use_custom_libcxx=false treat_warnings_as_errors=false use_ozone=true'```
libmediasoupclient version: branch v3, last commit 
``` 
SHA-1: cc511b8c4904ab86c82ba7626a1ddcba4e063d80

* Fix #79
```

```
/usr/local/bin/cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE="Debug" -DMEDIASOUPCLIENT_BUILD_TESTS:BOOL="True" -DLIBWEBRTC_INCLUDE_PATH=/mnt/sd0/libwebrtc/webrtc-checkout/src/  -DLIBWEBRTC_BINARY_PATH=/mnt/sd0/libwebrtc/webrtc-checkout/src/out/mybuild-m79-gcc6.3.0/obj/ -DCMAKE_INSTALL_PREFIX=$HOME/.vs/libmediasoupclient-v3/bfda7b43-4385-45be-abdc-e01c5759fb4a/out/install/Linux-GCC-Debug "/root/.vs/libmediasoupclient-v3/bfda7b43-4385-45be-abdc-e01c5759fb4a/src/CMakeLists.txt";
1> [CMake] 
1> [CMake] =========== libmediasoupclient Build Configuration ===========
1> [CMake] 
1> [CMake] -- MEDIASOUPCLIENT_BUILD_TESTS : True
1> [CMake] -- MEDIASOUPCLIENT_BUILD_DEMO  : ON
1> [CMake] -- MEDIASOUPCLIENT_LOG_TRACE   : OFF
1> [CMake] -- MEDIASOUPCLIENT_LOG_DEV     : OFF
1> [CMake] -- LIBWEBRTC_INCLUDE_PATH      : /mnt/sd0/libwebrtc/webrtc-checkout/src/
1> [CMake] -- LIBWEBRTC_BINARY_PATH       : /mnt/sd0/libwebrtc/webrtc-checkout/src/out/mybuild-m79-gcc6.3.0/obj/
1> [CMake] 
1> [CMake] status,use Threads::Threads
1> [CMake] -- Configuring done
1> [CMake] CMake Error at test/CMakeLists.txt:66 (add_library):
1> [CMake]   No SOURCES given to target: webrtc_extra
1> [CMake] 
1> [CMake] 
1> [CMake] CMake Generate step failed.  Build files cannot be regenerated correctly.
1> cd "/root/.vs/libmediasoupclient-v3/bfda7b43-4385-45be-abdc-e01c5759fb4a/out/build/Linux-GCC-Debug";/usr/local/bin/cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE="Debug" -DMEDIASOUPCLIENT_BUILD_TESTS:BOOL="True" -DLIBWEBRTC_INCLUDE_PATH=/mnt/sd0/libwebrtc/webrtc-checkout/src/  -DLIBWEBRTC_BINARY_PATH=/mnt/sd0/libwebrtc/webrtc-checkout/src/out/mybuild-m79-gcc6.3.0/obj/ -DCMAKE_INSTALL_PREFIX=$HOME/.vs/libmediasoupclient-v3/bfda7b43-4385-45be-abdc-e01c5759fb4a/out/install/Linux-GCC-Debug "/root/.vs/libmediasoupclient-v3/bfda7b43-4385-45be-abdc-e01c5759fb4a/src" 2>&1; 已返回，退出代码为 1

```

**Comment by jmillan** [comment]
Please open a topic in our discussion channel.

https://mediasoup.discourse.group/c/mediasoup-libraries/
