### ISSUE TITLE
DataConsumer::Close() crash

### ISSUE THREAD

**Issue by binxie33** [versatica/libmediasoupclient#94]
In DataConsumer::Close() we should UnregisterObserver first before closing, otherwise it will crash.

```
         /**
	 * Closes the DataConsumer.
	 */
	void DataConsumer::Close()
	{
		MSC_TRACE();

		if (this->closed)
			return;

		this->closed = true;
		this->dataChannel->UnregisterObserver();  // here is the fix
		this->dataChannel->Close();
		this->privateListener->OnClose(this);
	}
```

**Comment by jmillan** [comment]
does it actually crash currently?

**Comment by jmillan** [comment]
This should not be needed, otherwise we won't get the 'close' state changed from the underlaying datachannel.

More than that, if we get events from the underlaying datachannel after closing it, that would be a but in libwebrtc.
