### ISSUE TITLE
The Libmediasoupclient library USES Times' API /peer_connection_interface.h' File not Found in XCode

### ISSUE THREAD

**Issue by 435129214** [versatica/libmediasoupclient#96]
I've done a little bit of research on this, and it's under the SRC of WebRTC, but this is the file for the libmediasoupClient library, and the header file for the WebRTC library doesn't contain this file, and the header file for the libmediasoupClient library doesn't contain this file, so what's the reason.

![image](https://user-images.githubusercontent.com/16433951/90730130-30675080-e2fa-11ea-8474-2cf881558799.png)

**Comment by ibc** [comment]
Please, use the mediasoup forum for questions. This is not a bug but a bad usage.

**Comment by 435129214** [comment]
> Please, use the mediasoup forum for questions. This is not a bug but a bad usage.

what is the web address

**Comment by ibc** [comment]
Search for mediasoup forum in Google.

**Comment by 435129214** [comment]
I have registered an account, but I am not allowed to post after logging in. What should I do?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "versatica/libmediasoupclient"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月20日(星期四) 下午3:46
收件人:&nbsp;"versatica/libmediasoupclient"<libmediasoupclient@noreply.github.com&gt;;
抄送:&nbsp;"Horizon"<435129214@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [versatica/libmediasoupclient] The Libmediasoupclient library USES Times' API /peer_connection_interface.h' File not Found in XCode (#96)





 
Search for mediasoup forum in Google.

**Comment by ibc** [comment]
Your account is now validated and your message published in the forum.
