### ISSUE TITLE
error: use of enum ‘LogLevel’ without previous declaration

### ISSUE THREAD

**Issue by jackzhangkun** [versatica/libmediasoupclient#98]
libmediasoupclient/include/Logger.hpp:55:8:  warning: elaborated-type-specifier for a scoped enum must not use the ‘class’ keyword
   55 |   enum class LogLevel : uint8_t
      |   ~~~~ ^~~~~

libmediasoupclient/include/Logger.hpp:55:14: error: use of enum ‘LogLevel’ without previous declaration
   55 |   enum class LogLevel : uint8_t
      |              ^~~~~~~~

ubuntu version  20.04
gcc version 9.3.0
cmake version 3.18.2

**Comment by jmillan** [comment]
Should not be an issue since the addition of this https://github.com/versatica/libmediasoupclient/blob/v3/include/Logger.hpp#L46
